# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My Blogg Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  blogg_post_runner:
    runs-on: ubuntu-latest
    name: Blogg Post Manager Runner
    steps:
      # - id: file_changes
      #   uses: trilom/file-changes-action@v1.2.3
      #   with:
      #     output: "json" # optional output format
      - uses: lots0logs/gh-action-get-changed-files@2.0.6
        id: changed_files_actions
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Blogg Post Manager
        uses: ./ # Uses an action in the root directory
        id: postManager
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files_added: ${{ steps.changed_files_actions.outputs.added }} # Added files
          files_deleted: ${{ steps.changed_files_actions.outputs.deleted }} # Deleted files
          files_renamed: ${{ steps.changed_files_actions.outputs.renamed }} # Renamed files
          files_modified: ${{ steps.changed_files_actions.outputs.modified }} # Modified files
      - run: |
        cat ${HOME}/files.json
        cat ${HOME}/files_modified.json
        cat ${HOME}/files_added.json
        cat ${HOME}/files_deleted.json
