# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My Blogg Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  blogg_post_runner:
    runs-on: ubuntu-latest
    name: Blogg Post Manager Runner
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Blogg Post Manager
        uses: ./ # Uses an action in the root directory
        id: postManager
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files_added: ${{ steps.file_changes.outputs.files_added }}
          files_modified: ${{ steps.file_changes.outputs.files_modified }}
          files_removed: ${{ steps.file_changes.outputs.files_removed }}
