# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My Blogg Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  blogg_post_runner:
    runs-on: ubuntu-latest
    name: Blogg Post Manager Runner
    steps:
      # To use this repository's private action, you must check out the repository
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Blogg Post Manager
        uses: ./ # Uses an action in the root directory
        id: postManager
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Changed Files Exporter
        id: changedFiles
        uses: futuratrepadeira/changed-files@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '^.*\.(md|markdown)$'
      - run: echo "Created ${{ steps.changedFiles.outputs.files_created }}"
      - run: echo "Deleted ${{ steps.changedFiles.outputs.files_deleted }}"
